/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#00302b",
        "on-error-container": "#ffdad6",
        "primary-container": "#29a195",
        "surface-tint": "#6bd8cb",
        "surface-container-low": "#131b2f",
        "primary-fixed-dim": "#6bd8cb",
        "on-tertiary-container": "#292934",
        "secondary-container": "#464557",
        "outline": "#879391",
        "on-secondary": "#2f2f40",
        "on-primary-fixed": "#00201d",
        "tertiary-fixed-dim": "#c7c5d3",
        "on-surface-variant": "#bcc9c6",
        "on-secondary-container": "#b5b3c8",
        "tertiary-container": "#918f9d",
        "surface-container-high": "#22293f",
        "on-tertiary": "#302f3a",
        "inverse-on-surface": "#283045",
        "on-surface": "#dbe1fe",
        "background": "#0b1327",
        "on-tertiary-fixed-variant": "#464651",
        "secondary-fixed": "#e3e0f7",
        "secondary": "#c6c4da",
        "inverse-primary": "#006a61",
        "on-tertiary-fixed": "#1b1b25",
        "surface-container-highest": "#2d344a",
        "secondary-fixed-dim": "#c6c4da",
        "on-background": "#dbe1fe",
        "error-container": "#93000a",
        "surface": "#0b1327",
        "surface-dim": "#0b1327",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#005049",
        "surface-container": "#181f34",
        "inverse-surface": "#dbe1fe",
        "on-primary": "#003732",
        "primary-fixed": "#89f5e7",
        "surface-container-lowest": "#060d21",
        "tertiary-fixed": "#e4e1ef",
        "primary": "#6bd8cb",
        "tertiary": "#c7c5d3",
        "on-secondary-fixed-variant": "#464557",
        "outline-variant": "#3d4947",
        "surface-variant": "#2d344a",
        "on-secondary-fixed": "#1a1a2a",
        "surface-bright": "#31394f"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "stack-lg": "2rem",
        "stack-md": "1rem",
        "gutter": "1rem",
        "editor-max-width": "800px",
        "sidebar-width": "260px",
        "stack-xs": "0.25rem"
      },
      "fontFamily": {
        "body-lg": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "headline-md": ["Geist"],
        "quran-text": ["Amiri"],
        "quran-display": ["Amiri"],
        "body-md": ["Geist"]
      },
      "fontSize": {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "quran-text": ["32px", {"lineHeight": "56px", "fontWeight": "400"}],
        "quran-display": ["48px", {"lineHeight": "72px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
