// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBook(arg1) {
  return window['go']['main']['App']['AddBook'](arg1);
}

export function CompleteGoogleDriveAuth() {
  return window['go']['main']['App']['CompleteGoogleDriveAuth']();
}

export function CreateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3, arg4);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function ExportNoteToMarkdown(arg1, arg2) {
  return window['go']['main']['App']['ExportNoteToMarkdown'](arg1, arg2);
}

export function ExportVaultToMarkdown(arg1) {
  return window['go']['main']['App']['ExportVaultToMarkdown'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetAyahText(arg1, arg2) {
  return window['go']['main']['App']['GetAyahText'](arg1, arg2);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetExegesis(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetExegesis'](arg1, arg2, arg3);
}

export function GetExegesisPage(arg1, arg2) {
  return window['go']['main']['App']['GetExegesisPage'](arg1, arg2);
}

export function GetNotesForAyah(arg1, arg2) {
  return window['go']['main']['App']['GetNotesForAyah'](arg1, arg2);
}

export function GetQuranStructure() {
  return window['go']['main']['App']['GetQuranStructure']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function SaveNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartGoogleDriveAuth() {
  return window['go']['main']['App']['StartGoogleDriveAuth']();
}
