// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddBook(arg1:string):Promise<backend.BookMetadata>;

export function CompleteGoogleDriveAuth():Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:Array<any>):Promise<void>;

export function DeleteBook(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function ExportNoteToMarkdown(arg1:string,arg2:string):Promise<void>;

export function ExportVaultToMarkdown(arg1:string):Promise<void>;

export function GetAllNotes():Promise<Array<backend.NoteWithVerses>>;

export function GetAyahText(arg1:number,arg2:number):Promise<string>;

export function GetBooks():Promise<Array<backend.BookMetadata>>;

export function GetExegesis(arg1:string,arg2:number,arg3:number):Promise<backend.PageData>;

export function GetExegesisPage(arg1:string,arg2:number):Promise<backend.PageData>;

export function GetNotesForAyah(arg1:number,arg2:number):Promise<Array<backend.NoteWithVerses>>;

export function GetQuranStructure():Promise<Array<backend.Surah>>;

export function GetSettings():Promise<Record<string, string>>;

export function SaveNote(arg1:string,arg2:string,arg3:string,arg4:Array<any>):Promise<void>;

export function SaveSettings(arg1:Record<string, string>):Promise<void>;

export function StartGoogleDriveAuth():Promise<string>;
